export const ERROR = "ERROR";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const GETTOPIC = "GETTOPIC";

export const SEARCH_OPTIONS = "SEARCH_OPTIONS";

export const SEARCH_RESULTS_PROCESSING = "SEARCH_RESULTS_PROCESSING";
export const SEARCH_RESULTS_COMPLETED = "SEARCH_RESULTS_COMPLETED";