export const ERROR = "ERROR";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const GETTOPIC = "GETTOPIC";

export const COMMUNITY_SEARCH_OPTIONS = "COMMUNITY_SEARCH_OPTIONS";

export const COMMUNITY_SEARCH_RESULTS_PROCESSING = "COMMUNITY_SEARCH_RESULTS_PROCESSING";
export const COMMUNITY_SEARCH_RESULTS_COMPLETED = "COMMUNITY_SEARCH_RESULTS_COMPLETED";